scripts/scrumsys/administracion/urls.py
from django.conf.urls import url
from administracion.views import views_rol, views_user, view_project, view_dashboard, views, views_flujo, view_userstory, views_sprints, views_adjunto, nota_views



urlpatterns = [

      #usuarios
      url(r'^users/$', views_user.UserList.as_view(), name='user_list'),
      url(r'^(?P<pk>\d+)$', views_user.UserDetail.as_view(), name='user_detail'),
      url(r'^users/add/$', views_user.AddUser.as_view(), name="user_add"),
      url(r'^users/(?P<pk>\d+)/delete/$', views_user.DeleteUser.as_view(), name="user_delete"),
      url(r'^users/(?P<pk>\d+)/edit/$', views_user.EditUser.as_view(), name="user_edit"),

      #roles
      # url(r'^roles/$', views_rol.AddRol.rol_index.as_view(), name='rol_index'),
      url(r'^roles/$', views_rol.RolList.as_view(), name='rol_list'),
      url(r'^roles/(?P<pk>\d+)/$', views_rol.RolDetail.as_view(), name='rol_detail'),
      url(r'^roles/add/$', views_rol.AddRol.as_view(), name="rol_add"),
      url(r'^roles/(?P<pk>\d+)/edit/$', views_rol.EditRol.as_view(), name="rol_edit"),
      url(r'^roles/(?P<pk>\d+)/delete/$', views_rol.DeleteRolView.as_view(), name="rol_delete"),

      # dashboard
      url(r'^dashboard/backlog/$', view_dashboard.DashBacklog.as_view(), name='dash_backlog'),
      url(r'^dashboard/sprints/$', view_dashboard.DashSprint.as_view(), name='dash_sprint'),

      # proyecto
      url(r'^proyectos/$', view_project.ProjectList.as_view(), name='project_list'),
      url(r'^proyectos/agregar/$', view_project.ProjectCreate.as_view(), name='project_create'),
      url(r'^proyectos/$', views.projectPersonal, name='project'),
      url(r'^proyectos/(?P<pk>\d+)/$', view_project.ProjectDetail.as_view(), name='project_detail'),
      url(r'^proyectos/(?P<pk>\d+)/editar/$', view_project.ProjectUpdate.as_view(), name='project_update'),
      url(r'^proyectos/(?P<pk>\d+)/eliminar/$', view_project.ProjectDelete.as_view(), name='project_delete'),

      # flujos dentro del proyecto
      url(r'^proyectos/(?P<project_pk>\d+)/flujo/add/$', views_flujo.AddFlujo.as_view(), name="flujo_add"),
      url(r'^proyectos/(?P<project_pk>\d+)/flujo/$', views_flujo.FlujoList.as_view(), name='flujo_list'),
      url(r'^flujo/(?P<pk>\d+)/$', views_flujo.FlujoDetail.as_view(), name='flujo_detail'),
      url(r'^flujo/(?P<pk>\d+)/editar/$', views_flujo.UpdateFlujo.as_view(), name="flujo_update"),
      url(r'^flujo/(?P<pk>\d+)/eliminar/$', views_flujo.DeleteFlujo.as_view(), name="flujo_delete"),
      url(r'^flujo/(?P<pk>\d+)/sprint/(?P<sprint_pk>\d+)/$', views_flujo.FlujoDetailSprint.as_view(),name='flujo_detail_sprint'),

      # sprint dentro del proyecto 
      url(r'^proyectos/(?P<project_pk>\d+)/sprint/$', views_sprints.SprintList.as_view(), name='sprint_list'),
      url(r'^sprint/(?P<pk>\d+)/$', views_sprints.SprintDetail.as_view(), name='sprint_detail'),
      url(r'^proyectos/(?P<project_pk>\d+)/sprint/add/$', views_sprints.AddSprintView.as_view(), name="sprint_add"),
      url(r'^sprint/(?P<pk>\d+)/edit/$', views_sprints.UpdateSprintView.as_view(), name="sprint_update"),
      url(r'^sprint/(?P<pk>\d+)/eliminarus/$', views_sprints.DeleteUsSprintView.as_view(), name="sprint_delete_us"),
      url(r'^sprint/(?P<pk>\d+)/eliminarsprint/$', views_sprints.DeleteSprintView.as_view(), name="sprint_delete"),
      url(r'^sprint/(?P<pk>\d+)/reasignarus/$', views_sprints.Reasignar.as_view(), name="sprint_reasignar_us"),
      #url(r'^sprint/(?P<pk>\d+)/addUS/$', views_sprints.AddUsSprint.as_view(), name="add_US_sprint"),



      #user stories
      url(r'^proyectos/(?P<project_pk>\d+)/userstories/$', view_userstory.UserStoriesList.as_view(), name='product_backlog'),
      url(r'^proyectos/(?P<project_pk>\d+)/userstories/add/$', view_userstory.AddUserStory.as_view(),name="userstory_add"),
      url(r'^userstory/(?P<pk>\d+)/$', view_userstory.UserStoryDetail.as_view(), name='userstory_detail'),
      url(r'^userstory/(?P<pk>\d+)/version/$', view_userstory.VersionList.as_view(), name="version_list"),
      url(r'^userstory/(?P<pk>\d+)/editar/$', view_userstory.UpdateUserStory.as_view(), name="userstory_update"),
      url(r'^userstory/(?P<pk>\d+)/cancelar/$', view_userstory.CancelUserStory.as_view(), name="userstory_cancelar"),
      url(r'^userstory/(?P<pk>\d+)/registrar/$', view_userstory.RegistrarActividadUserStory.as_view(),name="userstory_registraractividad"),
      url(r'^userstory/(?P<pk>\d+)/registrodeactividad/$', nota_views.NotaList.as_view(),name="userstory_registrodeactividad"),
      url(r'^nota/(?P<pk>\d+)/$', nota_views.NotaDetail.as_view(), name='nota_detail'),
      url(r'^userstory/(?P<pk>\d+)/eliminardesprint/$', views_sprints.DeleteUsSprintView.as_view(), name="userstory_delete"),


      # adjunto
      url(r'^adjuntoarchivo/(?P<pk>\d+)/$', views_adjunto.download_attachment, name='download_attachment'),
      url(r'^userstory/(?P<pk>\d+)/archivos/$', views_adjunto.FileList.as_view(), name="file_list"),
      url(r'^userstory/(?P<pk>\d+)/archivos/subir/$', views_adjunto.UploadFileView.as_view(), name="file_upload"),
      url(r'^archivo/(?P<pk>\d+)/$', views_adjunto.FileDetail.as_view(), name="file_detail"),

      #no visto aun

      url(r'^userstory/(?P<pk>\d+)/aprobar/$', view_userstory.AprobarUserStory.as_view(), name="userstory_aprobar"),
      url(r'^userstory/(?P<pk>\d+)/rechazar/$', view_userstory.RechazarUserStory.as_view(), name="userstory_rechazar"),
      url(r'^proyectos/(?P<project_pk>\d+)/userstories/pendientes/$',view_userstory.AprobarPendientesUserStories.as_view(), name='pendientes_userstories'),

      url(r'^userstory/(?P<pk>\d+)/revert/(?P<version_pk>\d+)/$', view_userstory.UpdateVersion.as_view(), name="version_revert"),

]

scripts/scrumsys/scrumsys/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('autenticacion.urls')),
    url(r'', include('administracion.urls')),

]

scripts/scrumsys/administracion/models.py
# -*- coding: utf-8 -*-
from django.db.models.signals import m2m_changed
from guardian.shortcuts import assign_perm, remove_perm, get_perms_for_model, get_perms
from django.contrib.auth.models import User, Group
from django.core.exceptions import ValidationError
from django.db import models

from django.core.urlresolvers import reverse_lazy
# Create your models here.
from base64 import b64encode
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.utils.encoding import force_bytes
import reversion
from datetime import datetime
from django.db.models import Sum


class Proyecto(models.Model):
    """
    Modelo de Proyecto del sistema.

    """

    opciones_estado = (('PL', 'Planificacion'), ('EJ', 'Ejecutandose'), ('PE', 'Pendiente'), ('CA', 'Cancelado'), ('TE', 'Terminado'))
    nombre = models.CharField(max_length=40)
    estado = models.CharField(choices=opciones_estado, max_length=2, default='PE')
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_inicio = models.DateTimeField()
    fecha_fin = models.DateTimeField()
    equipo = models.ManyToManyField(User, through='MiembroEquipo')




    class Meta:
        # Los permisos estan asociados a los proyectos, entonces los permisos de ABM de las entidades
        #dependientes del proyecto, deben crearse como permisos de proyecto, aqui una lista
        #de permisos personalizados
        permissions = (

            #Permisos especificos del manejo de un proyecto
            ('listar_proyectos', 'Listar Proyectos'),
            ('ver_proyecto', 'Ver detalles del proyecto'),
            ('asignar_equipo', 'Asignar los miembros del equipo'),
            ('aprobar_proyecto', 'Aprobar el proyecto'),
            #permisos especificos para el manejo de sprint dentro del proyecto
            ('crear_sprint', 'Agregar Sprint'),
            ('editar_sprint', 'Editar Sprint'),
            ('eliminar_sprint', 'Eliminar Sprint'),
            ('ver_sprint', 'Ver Sprint'),
            # permisos especificos para el manejo de flujos dentro del proyecto
            ('crear_flujo', 'Agregar Flujo'),
            ('editar_flujo', 'Editar Flujo'),
            ('eliminar_flujo', 'Eliminar Flujo'),
            ('ver_flujo', 'Ver Flujo'),
            # permisos especificos para el manejo de User Storys dentro del proyecto
            ('crear_userstory', 'Agregar User Story'),
            ('editar_userstory', 'Editar User Story'),
            ('eliminar_userstory', 'Eliminar User Story'),
            ('registraractividad_userstory', 'Registrar avances en User Story'),
            ('aprobar_userstory', 'Aprobar User Story completado'),
            ('cancelar_userstory', 'Cancelar User Story completado'),
            ('priorizar_userstory', 'asignar prioridad a userstories'),
        )

    def __unicode__(self):
        return self.nombre

    def clean(self):
        #validacion de la fecha de inicio y final del proyecto
        try:
            if self.fecha_inicio > self.fecha_fin:
                raise ValidationError({'fecha_inicio': 'Fecha de inicio no puede ser mayor que la fecha de terminacion.'})
        except TypeError:
            pass  # error si una de las fechas es null

    def get_absolute_url(self):
        return reverse_lazy('project_detail', args=[self.pk])

    def get_horas_estimadas(self):
        return self.userstory_set.aggregate(total=Sum('tiempo_estimado'))['total']

    def get_horas_trabajadas(self):
        return self.userstory_set.aggregate(total=Sum('tiempo_registrado'))['total']

    def get_progreso(self):
        us_total = self.userstory_set.count() - self.userstory_set.filter(estado=4).count()
        us_aprobados = self.userstory_set.filter(estado_actividad=2).count()
        if us_total > 0 :
            progreso = float(us_aprobados) / us_total * 100 
            return int(progreso)
        else:
            return 0
    progreso = property(get_progreso)

    def get_us_completados(self):
        us_aprobados = self.userstory_set.filter(estado_actividad=2).count()
        return int(us_aprobados)
    us_completados = property(get_us_completados)

    def get_us_faltantes(self):
        us_total = self.userstory_set.count() - self.userstory_set.filter(estado=4).count()
        us_aprobados = self.userstory_set.filter(estado_actividad=2).count()
        if us_total > 0 :
            us_faltantes = us_total -  float(us_aprobados)
            return int(us_faltantes)
        else:
            return 0
    us_faltantes = property(get_us_faltantes)

    def get_sprints(self):
        sprints = self.sprint_set.all()
        return sprints
    sprints = property(get_sprints)

    def count_sprints(self):
        sprints = self.sprint_set.count()
        return sprints
    tot_sprints = property(count_sprints)

    def get_sprints_completados(self):
        sprints_aprobados = self.sprint_set.filter(estado='TE').count()
        return int(sprints_aprobados)
    sprints_completados = property(get_sprints_completados)

    def get_sprints_faltantes(self):
        sprints_total = self.sprint_set.count()
        sprints_aprobados = self.sprint_set.filter(estado='TE').count()
        if sprints_total > 0 :
            sprints_faltantes = sprints_total -  float(sprints_aprobados)
            return int(sprints_faltantes)
        else:
            return 0
    sprints_faltantes = property(get_sprints_faltantes)

    def get_progreso_sprints(self):
        sprints_total = self.sprint_set.count()
        sprints_aprobados = self.sprint_set.filter(estado='TE').count()
        if sprints_total > 0 :
            progreso = float(sprints_aprobados) / sprints_total * 100 
            return int(progreso)
        else:
            return 0
    progreso_sprints = property(get_progreso_sprints)

    def eliminar_proyecto(self):
        self.estado = 'CA'

class MiembroEquipo(models.Model):
    """
    Miembros del equipo de un proyecto
    """

    usuario = models.ForeignKey(User)
    proyecto = models.ForeignKey(Proyecto)
    roles = models.ManyToManyField(Group)

    def __unicode__(self):
        return self.usuario.username

    def save(self, force_insert=False, force_update=False, using=None,update_fields=None):
        super(MiembroEquipo, self).save(force_insert, force_update, using, update_fields)
        # Agregamos el permiso ver_proyecto al usuario
        assign_perm('ver_proyecto', self.usuario, self.proyecto)

    def delete(self, using=None):
        for role in self.roles.all():
            for perm in role.permissions.all():
                remove_perm(perm.codename, self.usuario, self.proyecto)
        super(MiembroEquipo, self).delete(using)

    class Meta:
        default_permissions = ()
        verbose_name_plural = 'miembros equipo'
        unique_together = ('usuario', 'proyecto')


class Sprint(models.Model):
    """
    Manejo de los sprints del proyecto
    """
    opciones_estado = (('PL', 'Planificacion'), ('EJ', 'Ejecutandose'), ('PE', 'Pendiente'), ('CA', 'Cancelado'), ('TE', 'Terminado'))
    nombre = models.CharField(max_length=20)
    fecha_inicio = models.DateTimeField()
    fecha_fin = models.DateTimeField()
    proyecto = models.ForeignKey(Proyecto, null=False, blank=True)
    estado = models.CharField(choices=opciones_estado, max_length=2, default='PE')
    equipo = models.ManyToManyField(User, through='MiembroEquipoSprint')
    duracion_sprint = models.PositiveIntegerField(default=30)
    horasRegistradaSprint = models.PositiveIntegerField(default=0)
    horasDuracionSprint = models.PositiveIntegerField(default=0)

    class Meta:
        default_permissions = ()
        verbose_name = 'sprint'
        verbose_name_plural = 'sprints'

    def clean(self):
        aux = Sprint.objects.filter(estado='EJ', proyecto=self.proyecto)
        try:
            if aux.first() != self and self.estado == 'EJ' and aux.count() > 0:
                raise ValidationError({'estado': 'Ya existe un sprint ejecutandose'})
        except TypeError:
            pass  # error si una de las fechas es null

    def sumarHoras(self):
        self.horasDuracionSprint = 0
        for miembro in MiembroEquipoSprint.objects.filter(sprint=self):
             self.horasDuracionSprint += miembro.horasDeTrabajo
        self.horasDuracionSprint *= self.duracion_sprint

    def registrarHoras(self):
        self.horasRegistradaSprint = 0
        for us in UserStory.objects.filter(sprint=self):
            self.horasRegistradaSprint += us.tiempo_estimado

    def __unicode__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse_lazy('sprint_detail', args=[self.pk])

    def get_us_sprint(self):
        us_total = UserStory.objects.filter(sprint=self).count()
        us_aprobados = UserStory.objects.filter(sprint=self).filter(estado_actividad=2).count()
        
        if us_total > 0 :
            progreso = float(us_aprobados) / us_total * 100 
            return int(progreso)
        else:
            return 0
    us_sprint = property(get_us_sprint)

    def eliminar_sprint(self):
        self.estado = 'CA'

class MiembroEquipoSprint(models.Model):
    """
    Miembros del equipo de un sprint
    """
    usuario = models.ForeignKey(User)
    sprint = models.ForeignKey(Sprint)
    horasDeTrabajo=models.PositiveIntegerField(default=0)

    def __unicode__(self):
        return self.usuario.username

    class Meta:
        default_permissions = ()
        verbose_name_plural = 'miembros equipo sprint'
        unique_together = ('usuario', 'sprint')


class Flujo(models.Model):
    """
    Administración de los flujos que forman parte de un proyecto.
    """
    nombre = models.CharField(max_length=20)
    proyecto = models.ForeignKey(Proyecto, null=True, blank=True)

    def __unicode__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = 'flujos'
        default_permissions = ()



    def get_absolute_url(self):

scripts/scrumsys/templates/administracion/proyecto/project_delete.html
{% extends 'administracion/base.html' %}
{% block contentbase %}

		<div class="row">
			<ol class="breadcrumb">
				<li><a href="{% url "index" %}"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
 
				<li class="active">Eliminar Proyecto </li>
			</ol>
		</div><!--/.row-->

     	<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
		
		<ul class="nav menu">
		<li><a href="#" data-toggle="dropdown"><svg class="glyph stroked dashboard-dial"><use xlink:href="#stroked-dashboard-dial"></use></svg> Dashboard</a>
                <ul class="dropdown-menu" role="menu">
					<li><a href='/dashboard/backlog'><svg class="glyph stroked table"><use xlink:href="#stroked-table"/></svg> Product Backlog</a></li>
					<li><a href='/dashboard/sprints'><svg class="glyph stroked calendar"><use xlink:href="#stroked-calendar"/></svg> Sprints </a></li>
				</ul>
			</li>
			<li><a href="{% url 'project' %}"><svg class="glyph stroked dashboard-dial"><use xlink:href="#stroked-dashboard-dial"></use></svg> Proyectos</a></li>
            <li><a href="{% url 'user_list' %}"><svg class="glyph stroked male user "><use xlink:href="#stroked-male-user"/></svg> Usuarios</a></li>
            <li class="active"><a href="{% url 'rol_list' %}"><svg class="glyph stroked key "><use xlink:href="#stroked-key"/></svg> Roles</a></li>

        </ul>


	</div><!--/.sidebar-->



{% block header %}{{ group }}{% endblock %}

<form action="" method="post" role="form"> {% csrf_token %}

    <div class="form-group">
        <p>Seguro de que desea eliminar el proyecto?</p>
    </div>

    <input type="submit" value="Confirmar" class="btn btn-danger"/>
</form>
{% endblock %}

scripts/scrumsys/templates/administracion/proyecto/project_detail.html
{% extends 'administracion/base.html' %}
{% load guardian_tags %}
{% block contentbase %}



    <div class="row">
   <ol class="breadcrumb">
      <li><a href="{% url "index" %}"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
      <li><a href="{%url "project_list" %}">Lista de Proyectos</a></li>
       <li class="active">Detalles de Proyecto</li>
   </ol>
</div><!--/.row-->





    <div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
		<ul class="nav menu">
        <li><a href="#" data-toggle="dropdown"><svg class="glyph stroked dashboard-dial"><use xlink:href="#stroked-dashboard-dial"></use></svg> Dashboard</a>
                <ul class="dropdown-menu" role="menu">
					<li><a href='/dashboard/backlog'><svg class="glyph stroked table"><use xlink:href="#stroked-table"/></svg> Product Backlog</a></li>
					<li><a href='/dashboard/sprints'><svg class="glyph stroked calendar"><use xlink:href="#stroked-calendar"/></svg> Sprints </a></li>
				</ul>
			</li>
			<li class="active"><a href="{% url 'project_list' %}"><svg class="glyph stroked dashboard-dial"><use xlink:href="#stroked-dashboard-dial"></use></svg> Proyectos</a></li>
            <li><a href="{% url 'user_list' %}"><svg class="glyph stroked male user "><use xlink:href="#stroked-male-user"/></svg> Usuarios</a></li>
            <li><a href="{% url 'rol_list' %}"><svg class="glyph stroked key "><use xlink:href="#stroked-key"/></svg> Roles</a></li>

        </ul>
    </div>
    {% get_obj_perms user for proyecto as "proyecto_perms" %}
    <h3>{{ proyecto.nombre }}</h3>


    <ul class="list-inline">
        <a href="{% url 'product_backlog' proyecto.id %}"><i class="glyphicon glyphicon-eye-open"></i>Ver Product Backlog</a>    |

        {% if 'change_proyecto' in proyecto_perms %}<li><a href="{% url 'project_update' proyecto.id %}" class="glyphicon glyphicon-pencil">Editar</a></li>{% endif %}


    </ul>

    <div class="row">
        <div class="col-lg-4">
            <div class="well">
                <p><strong>Estado:</strong> {{ proyecto.get_estado_display }}</p>

                <p><strong>Fecha de Inicio:</strong> {{ proyecto.fecha_inicio|date }}</p>

                <p><strong>Fecha de Finalizacion:</strong> {{ proyecto.fecha_fin|date }}</p>


            </div>
        </div>
        <div class="col-lg-4">

        </div>

    </div>



    <div class="row">
            <div class="col-lg-4">
                <h4 class="list-group-item-heading">
                    <a href="{% if perms.proyecto.change_proyecto %}
                    {% url 'project_update' proyecto.id %}#equipo
                    {% else %}#{% endif %}">Equipo</a>
                </h4>
                <div class="list-group">
                    {% for m in team %}
                        <a href="{% url 'user_detail' m.usuario_id %}" class="list-group-item">
                            {{ m.usuario }}
                            {% for r in m.roles.all %}
                                <span class="badge" data-toggle="tooltip" data-placement="left"
                                  title="Rol">{{ r }}</span>
                            {% endfor %}
                        </a>
                    {% endfor %}
                </div>
            </div>
            <div class="col-lg-4">
                <h4 class="list-group-item-heading"><a href="{% url 'sprint_list' proyecto.id %}">Sprints</a></h4>
                <div class="list-group">
    
                        {% for s in sprints %}
                            {% ifnotequal s.estado 'CA' %}
                        <a href="{% url 'sprint_detail' s.id %}" class="list-group-item">{{ s.nombre }}
                            <span class="badge" data-toggle="tooltip" data-placement="right"
                                  title="Fecha de Inicio">{{ s.userstory_set.count }}</span>
                        </a>
                               {% endifnotequal %}
                    {% endfor %}
    
                </div>
            </div>

        <div class="row">

            <div class="col-lg-4">
                    <h4 class="list-group-item-heading"><a href="{% url 'flujo_list' proyecto.id %}">Flujos</a></h4>

                    <div class="list-group">
                        {% for f in flujos %}
                            <a href="{% url 'flujo_detail' f.id %}" class="list-group-item">{{ f.nombre }}
                                <span class="badge" data-toggle="tooltip" data-placement="right"
                                    title="Actividades">{{ f.actividad_set.count }}</span>
                            </a>
                        {% endfor %}
                    </div>
            </div>

            

        </div>


{% endblock %}

scripts/scrumsys/templates/administracion/proyecto/project_list.html
{% extends 'administracion/base.html' %}
{% load guardian_tags %}

{% block contentbase %}




		<div class="row">
			<ol class="breadcrumb">
				<li><a href="{% url "index" %}"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
				<li class="active">Lista de Proyectos</li>
			</ol>
		</div><!--/.row-->

        <div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">

		
		<ul class="nav menu">
        <li><a href="#" data-toggle="dropdown"><svg class="glyph stroked dashboard-dial"><use xlink:href="#stroked-dashboard-dial"></use></svg> Dashboard</a>
                <ul class="dropdown-menu" role="menu">
					<li><a href='/dashboard/backlog'><svg class="glyph stroked table"><use xlink:href="#stroked-table"/></svg> Product Backlog</a></li>
					<li><a href='/dashboard/sprints'><svg class="glyph stroked calendar"><use xlink:href="#stroked-calendar"/></svg> Sprints </a></li>
				</ul>
			</li>
			<li class="active"><a href="{% url 'project_list' %}"><svg class="glyph stroked dashboard-dial"><use xlink:href="#stroked-dashboard-dial"></use></svg> Proyectos</a></li>
            <li><a href="{% url 'user_list' %}"><svg class="glyph stroked male user "><use xlink:href="#stroked-male-user"/></svg> Usuarios</a></li>
            <li><a href="{% url 'rol_list' %}"><svg class="glyph stroked key "><use xlink:href="#stroked-key"/></svg> Roles</a></li>

        </ul>
    </div>

{% if perms.administracion.add_proyecto %}
            <div class="col-xs-12 col-md-6 col-lg-3">

    <a href="{% url 'project_create' %}">
				<div class="panel panel-blue panel-widget ">

					<div class="row no-padding">
						<div class="col-sm-3 col-lg-5 widget-left">

							<svg class="glyph stroked plus sign"><use xlink:href="#stroked-plus-sign"/></svg>
						</div>
						<div class="col-sm-9 col-lg-7 widget-right">
							<div class="large">Crear</div>
							<div class="text-muted">Proyecto</div>
						</div>
					</div>
				</div>
        </a>

    </div>

{% endif %}



		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">Lista de proyectos</div>
					
                         <div class="fixed-table-container"><div class="fixed-table-header"><table></table></div>
                             <div class="fixed-table-body"><div class="fixed-table-loading" style="top: 37px; display: none;">Loading, please wait…</div>
                                 <table data-toggle="table" data-url="tables/data1.json" data-show-refresh="true" data-show-toggle="true" data-show-columns="true"
                                        data-search="true" data-select-item-name="toolbar1" data-pagination="true" data-sort-name="name" data-sort-order="desc" class="table table-hover">

                                   {% block thead %}
                                        <th>Nombre</th>
                                        <th>Estado</th>
                                        <th>Fecha de Inicio</th>
                                        <th>Fecha de Finalizacion</th>
                                        <th>Detalles del proyecto</th>
                                        <th>Editar Proyecto</th>
                                        <th>Eliminar</th>
                                   {% endblock %}
                                    {% block tbody %}

                                    

                                    {% for p in proyecto %}
                                    {% ifnotequal p.estado 'CA' %}
                                            {% get_obj_perms user for p as "proyecto_perms" %}


                                            <tr data-index={{ p.id }}>

                                                <td style>{{ p.nombre|title }}</td>
                                                <td style>{{ p.get_estado_display }}</td>
                                                <td style>{{ p.fecha_inicio|date:"SHORT_DATE_FORMAT" }}</td>
                                                <td style>{{ p.fecha_fin|date:"SHORT_DATE_FORMAT" }}</td>

                                                <td style>
                                                
                                                    {% if "ver_proyecto" in proyecto_perms %}
                                                         <a href="{{ p.get_absolute_url }}"><button type="submit" class="btn btn-default btn-md">Ver</button></a>
                                                     {% endif %}
                                                
                                                </td>
                                                <td style>
                                                    {% if "change_proyecto" in proyecto_perms %}
                                                         <a href="{% url 'project_update' p.id %}"><button type="submit" class="btn btn-warning btn-md">Editar</button></a>
                                                    {% endif %}

                                                </td>
                                                                                                <td style>
                                                    {% if "change_proyecto" in proyecto_perms %}
                                                         <a href="{% url 'project_delete' p.id %}"><button type="submit" class="btn btn-danger btn-md">Eliminar</button></a>
                                                    {% endif %}

                                                </td>
                                            </tr>
{% endifnotequal %}

                                        {% endfor %}


                                    {% endblock %}

                            </table>
                        </div>				
                    </div>
			</div>
		</div>


{% endblock %}